Fix compiling FB commandline programs on Windows due to missing libfbgfx
Logs showed relump.exe failing with "undefined reference to `fb_GfxScreen@20'"

git-svn-id: https://rpg.hamsterrepublic.com/source/wip@13022 7d344553-34f0-0310-a9b1-970ce8f1c3a2