Fix checked_system on Android
Need to include sys/wait.h. And for some reason, including this
header after some others causes "undefined reference to mkfifo/signal"
linker errors!

git-svn-id: https://rpg.hamsterrepublic.com/source/wip@8499 7d344553-34f0-0310-a9b1-970ce8f1c3a2