Fix compile error on Mac OS 10.13 due to warn_unused_result name clash
Error:
 In file included from os_unix_wm.c:21:
 (...)
 In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:34:
 /System/Library/Frameworks/Security.framework/Headers/SecRandom.h:60:21: error: use of undeclared identifier '__warn_unused_result__'
     __attribute__ ((warn_unused_result))
                     ^
 ./config.h:198:45: note: expanded from macro 'warn_unused_result'
 # define warn_unused_result __attribute__ ((__warn_unused_result__))

git-svn-id: https://rpg.hamsterrepublic.com/source/wip@11464 7d344553-34f0-0310-a9b1-970ce8f1c3a2